6-firstdirectory

diff --git a/0x00-shell_basics/git command b/0x00-shell_basics/git command
--- a/0x00-shell_basics/git command
+++ b/0x00-shell_basics/git command
@@ -1,5 +1,11 @@
 #!/bin/bash
-read -p file
-git add .
-git commit -m "$file"
+
+if [ $# -eq 0 ]; then
+  echo "Error: No file name provided."
+  exit 1
+fi
+
+file = $1
+git add "$file"
+git commit -m "Add file: $file"
 git push
